accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = "accounts"

urlpatterns = [
    path("register/", register, name="register"),
    path("accounts/login/", login_view, name="user_login"),
    path("accounts/logout/", login_view, name="user_logout"),
    path("", dashboard_view, name="dashboard"),
]

apis/urls.py
from django.urls import path
from apis.views import *

app_name = "apis"

urlpatterns = [
    path("register/", register_users_api, name="visitor_register_api"),
    path("login/", login_user_api, name="visitor_login_api"),
    path("user/", visitor_data, name="visitor_data_api"),
    path("check_in_out/", visitor_checkin_checkout, name="visitor_checkin_out_api"),
    # path("check_out/", check_out_view, name="visitor_checkout"),
]

safeentry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("apis.urls")),
    path("", include("accounts.urls")),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models/company.py
# from accounts.models.user import User
import uuid
from django.db import models


class Company(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # new
    owner = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="companies"
    )
    business_name = models.CharField(max_length=200)
    business_address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    business_phone = models.CharField(max_length=50)
    business_email = models.EmailField(max_length=254)
    business_registration_number = models.CharField(max_length=50)

    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=False)

    # def __str__(self):
    #     return self.business_name

accounts/models/user.py
from accounts.models.company import Company
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    phone = models.CharField(max_length=50, unique=True)
    identity_number = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    post_code = models.CharField(max_length=7, null=True)

    visited = models.ManyToManyField(
        Company,
        through="CompanyUser",
        through_fields=(
            "user",
            "company",
        ),
    )

    is_visitor = models.BooleanField("visitor status", default=False)
    is_company = models.BooleanField("company status", default=False)

    def full_name(self):
        return self.first_name + " " + self.last_name


class CompanyUser(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # new
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name="company_visitors"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="company_visited"
    )

    checked_in = models.DateTimeField(auto_now_add=True)
    checked_out = models.DateTimeField(auto_now=True, null=True)

    # def __str__(self):
    #     return self.company.business_name + " : " + self.user.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models.user import User
from django import forms


class RegiserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password",
            # "address",
            # "city",
            # "phone",
            "identity_number",
            # "post_code",
            # "is_company",
        ]

accounts/views.py
from accounts.forms import RegiserForm
from django.contrib import messages
from accounts.models.company import Company
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework import exceptions
from accounts.models.user import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from rest_framework.decorators import api_view
import qrcode

# Create your views here.


def register(request):
    # qr = qrcode.QRCode(version=1, box_size=10, border=5)
    # company = Company.objects.all()
    # qr.add_data({"company": str(company[0].id), "dev": "ap1"})
    # qr.make(fit=True)
    # img = qr.make_image(fill_color="black", back_color="white").convert("RGB")
    # img.save("sample.jpg")
    if request.method == "POST":
        register_form = RegiserForm(request.POST)

        if register_form.is_valid():
            register.save()
            return redirect("accounts:dashboard")
    register_form = RegiserForm()
    context = {"register_form": register_form}
    return render(request, "accounts/register.html", context)


def login_view(request):
    if request.method == "POST":
        identity_number = request.POST.get("identity_number")
        password = request.POST.get("password")

        if (identity_number is None) or (password is None):
            messages.error(request, "No identity number or password")
            return redirect("accounts:user_login")

        user = User.objects.get(identity_number=identity_number)

        if user is None:
            messages.error(request, "user not found")
            return redirect("accounts:user_login")

        if not user.check_password(password):
            messages.error(request, "password incorrect")
            return redirect("accounts:user_login")

        login(request, user)
        return redirect("accounts:dashboard")

    return render(request, "accounts/login.html")


def logout_view(request):
    logout(request)
    return redirect("accounts:user_login")


@login_required
def dashboard_view(request):
    return render(request, "accounts/dashboard.html")

accounts/templates/accounts/partials/header.html
{% load static %}
<header class="mdc-top-app-bar">
  <div class="mdc-top-app-bar__row">
    <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <button
        class="
          material-icons
          mdc-top-app-bar__navigation-icon
          mdc-icon-button
          sidebar-toggler
        "
      >
        menu
      </button>
      <span class="mdc-top-app-bar__title"
        >Greetings {{request.user.username | capfirst}}!</span
      >
      <div
        class="
          mdc-text-field
          mdc-text-field--outlined
          mdc-text-field--with-leading-icon
          search-text-field
          d-none d-md-flex
        "
      >
        <i class="material-icons mdc-text-field__icon">search</i>
        <input class="mdc-text-field__input" id="text-field-hero-input" />
        <div class="mdc-notched-outline">
          <div class="mdc-notched-outline__leading"></div>
          <div class="mdc-notched-outline__notch">
            <label for="text-field-hero-input" class="mdc-floating-label"
              >Search..</label
            >
          </div>
          <div class="mdc-notched-outline__trailing"></div>
        </div>
      </div>
    </div>
    <div
      class="
        mdc-top-app-bar__section
        mdc-top-app-bar__section--align-end
        mdc-top-app-bar__section-right
      "
    >
      <div class="menu-button-container menu-profile d-none d-md-block">
        <button class="mdc-button mdc-menu-button">
          <span class="d-flex align-items-center">
            <span class="figure">
              <img
                src="{% static 'assets/images/faces/face1.jpg' %}"
                alt="user"
                class="user"
              />
            </span>
            <span class="user-name">
              {{request.user.first_name | capfirst}}</span
            >
          </span>
        </button>
        <div class="mdc-menu mdc-menu-surface" tabindex="-1">
          <ul
            class="mdc-list"
            role="menu"
            aria-hidden="true"
            aria-orientation="vertical"
          >
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-account-edit-outline text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Edit profile</h6>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-settings-outline text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Logout</h6>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="divider d-none d-md-block"></div>
      <div class="menu-button-container d-none d-md-block">
        <button class="mdc-button mdc-menu-button">
          <i class="mdi mdi-settings"></i>
        </button>
        <div class="mdc-menu mdc-menu-surface" tabindex="-1">
          <ul
            class="mdc-list"
            role="menu"
            aria-hidden="true"
            aria-orientation="vertical"
          >
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-alert-circle-outline text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Settings</h6>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-progress-download text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Update</h6>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="menu-button-container">
        <button class="mdc-button mdc-menu-button">
          <i class="mdi mdi-bell"></i>
        </button>
        <div class="mdc-menu mdc-menu-surface" tabindex="-1">
          <h6 class="title">
            <i class="mdi mdi-bell-outline mr-2 tx-16"></i> Notifications
          </h6>
          <ul
            class="mdc-list"
            role="menu"
            aria-hidden="true"
            aria-orientation="vertical"
          >
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon">
                <i class="mdi mdi-email-outline"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  You received a new message
                </h6>
                <small class="text-muted"> 6 min ago </small>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon">
                <i class="mdi mdi-account-outline"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  New user registered
                </h6>
                <small class="text-muted"> 15 min ago </small>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon">
                <i class="mdi mdi-alert-circle-outline"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">System Alert</h6>
                <small class="text-muted"> 2 days ago </small>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon">
                <i class="mdi mdi-update"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  You have a new update
                </h6>
                <small class="text-muted"> 3 days ago </small>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="menu-button-container">
        <button class="mdc-button mdc-menu-button">
          <i class="mdi mdi-email"></i>
          <span class="count-indicator">
            <span class="count">3</span>
          </span>
        </button>
        <div class="mdc-menu mdc-menu-surface" tabindex="-1">
          <h6 class="title">
            <i class="mdi mdi-email-outline mr-2 tx-16"></i> Messages
          </h6>
          <ul
            class="mdc-list"
            role="menu"
            aria-hidden="true"
            aria-orientation="vertical"
          >
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail">
                <img
                  src="{% static 'assets/images/faces/face4.jpg' %}"
                  alt="user"
                />
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  Mark send you a message
                </h6>
                <small class="text-muted"> 1 Minutes ago </small>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail">
                <img
                  src="{% static 'assets/images/faces/face2.jpg' %}"
                  alt="user"
                />
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  Cregh send you a message
                </h6>
                <small class="text-muted"> 15 Minutes ago </small>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail">
                <img
                  src="{% static 'assets/images/faces/face3.jpg' %}"
                  alt="user"
                />
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">
                  Profile picture updated
                </h6>
                <small class="text-muted"> 18 Minutes ago </small>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="menu-button-container d-none d-md-block">
        <button class="mdc-button mdc-menu-button">
          <i class="mdi mdi-arrow-down-bold-box"></i>
        </button>
        <div class="mdc-menu mdc-menu-surface" tabindex="-1">
          <ul
            class="mdc-list"
            role="menu"
            aria-hidden="true"
            aria-orientation="vertical"
          >
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-lock-outline text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Lock screen</h6>
              </div>
            </li>
            <li class="mdc-list-item" role="menuitem">
              <div class="item-thumbnail item-thumbnail-icon-only">
                <i class="mdi mdi-logout-variant text-primary"></i>
              </div>
              <div
                class="
                  item-content
                  d-flex
                  align-items-start
                  flex-column
                  justify-content-center
                "
              >
                <h6 class="item-subject font-weight-normal">Logout</h6>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

accounts/templates/accounts/partials/navbar.html
{% load static %}
<aside class="mdc-drawer mdc-drawer--dismissible mdc-drawer--open">
  <div class="mdc-drawer__header">
    <a href="index.html" class="brand-logo">
      <img src="{% static 'accounts/images/logo.svg' %}" alt="logo" />
    </a>
  </div>
  <div class="mdc-drawer__content">
    <div class="user-info">
      <p class="name">{{request.user.full_name}}</p>
      <p class="email">{{request.user.email}}</p>
    </div>
    <div class="mdc-list-group">
      <nav class="mdc-list mdc-drawer-menu">
        <div class="mdc-list-item mdc-drawer-item">
          <a class="mdc-drawer-link" href="{% url 'accounts:dashboard' %}">
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >home</i
            >
            Dashboard
          </a>
        </div>
        {% comment %}
        <div class="mdc-list-item mdc-drawer-item">
          <a class="mdc-drawer-link" href="pages/forms/basic-forms.html">
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >track_changes</i
            >
            Forms
          </a>
        </div>
        <div class="mdc-list-item mdc-drawer-item">
          <a
            class="mdc-expansion-panel-link"
            href="#"
            data-toggle="expansionPanel"
            data-target="ui-sub-menu"
          >
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >dashboard</i
            >
            UI Features
            <i class="mdc-drawer-arrow material-icons">chevron_right</i>
          </a>
          <div class="mdc-expansion-panel" id="ui-sub-menu">
            <nav class="mdc-list mdc-drawer-submenu">
              <div class="mdc-list-item mdc-drawer-item">
                <a
                  class="mdc-drawer-link"
                  href="pages/ui-features/buttons.html"
                >
                  Buttons
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a
                  class="mdc-drawer-link"
                  href="pages/ui-features/typography.html"
                >
                  Typography
                </a>
              </div>
            </nav>
          </div>
        </div>
        <div class="mdc-list-item mdc-drawer-item">
          <a class="mdc-drawer-link" href="pages/tables/basic-tables.html">
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >grid_on</i
            >
            Tables
          </a>
        </div>
        <div class="mdc-list-item mdc-drawer-item">
          <a class="mdc-drawer-link" href="pages/charts/chartjs.html">
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >pie_chart_outlined</i
            >
            Charts
          </a>
        </div>
        <div class="mdc-list-item mdc-drawer-item">
          <a
            class="mdc-expansion-panel-link"
            href="#"
            data-toggle="expansionPanel"
            data-target="sample-page-submenu"
          >
            <i
              class="
                material-icons
                mdc-list-item__start-detail
                mdc-drawer-item-icon
              "
              aria-hidden="true"
              >pages</i
            >
            Sample Pages
            <i class="mdc-drawer-arrow material-icons">chevron_right</i>
          </a>
          <div class="mdc-expansion-panel" id="sample-page-submenu">
            <nav class="mdc-list mdc-drawer-submenu">
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/blank-page.html">
                  Blank Page
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/403.html">
                  403
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/404.html">
                  404
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/500.html">
                  500
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/505.html">
                  505
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/login.html">
                  Login
                </a>
              </div>
              <div class="mdc-list-item mdc-drawer-item">
                <a class="mdc-drawer-link" href="pages/samples/register.html">
                  Register
                </a>
              </div>
            </nav>
          </div>
        </div>
        {% endcomment %}
      </nav>
    </div>
    <div class="profile-actions">
      <a href="javascript:;">Settings</a>
      <span class="divider"></span>
      <a href="{% url 'accounts:user_logout' %}">Logout</a>
    </div>
  </div>
</aside>